### ISSUE TITLE
Could you tell me where the source code for other prefetchers that in paper is available?

### ISSUE THREAD

**Issue by w1nda** [car3s/IPCP_ISCA2020#1]
> "We compare the effec- tiveness of IPCP with L1 prefetchers like NL, Stream, BOP, VLDP, SPP, DSPatch, MLOP, TSKID, DOL, SMS, and Bingo."

Could you tell me where the source code for these prefetchers is available?

**Comment by w1nda** [comment]
please ❤️
i'll very appreciate it

**Comment by biswabandan** [comment]
Most of the source codes are available either through ChampSim or from DPC-2 and DPC-3 sites.

**Comment by w1nda** [comment]
> Most of the source codes are available either through ChampSim or from DPC-2 and DPC-3 sites.

thank you
